### ISSUE TITLE
add war 

### ISSUE THREAD

**Issue by piincher** [mdtalalwasim/Doctor-Patient-Portal-AdvanceJavaWebProject#1]
hello ,can you please add the war file i would like to test myself it seems to be an interesting project

**Comment by mdtalalwasim** [comment]
Thank you for your interest. Let me check, Later I'll upload it.

**Comment by piincher** [comment]
Ok I'm waiting for you to upload the file .Thanks

**Comment by piincher** [comment]
@mdtalalwasim Hello again any update about the war file ?
